"""empty message

Revision ID: d5245225b328
Revises: de65e56818e4
Create Date: 2020-09-09 19:11:03.851427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5245225b328'
down_revision = 'de65e56818e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_email', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'user', ['hash_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'hash_email')
    # ### end Alembic commands ###
